owner: text-forge
repo: uptime

sites:
  - name: text-forge.github.io
    url: https://text-forge.github.io
  - name: Docs
    url: https://text-forge.github.io/docs
  - name: Online Marketplace
    url: https://text-forge.github.io/marketplace
  - name: Marketplace API (Packages Information)
    url: https://raw.githubusercontent.com/text-forge/mp/refs/heads/main/packages.json

assignees:
  - mkh-user

skipDeleteIssues: true
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

status-website:
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/text-forge/text-forge/main/icon.png
  name: Text Forge Status
  introTitle: "**Text Forge** Uptime Monitoring"
  introMessage: "Pings and uptimes for various endpoints and services from [Text Forge](https://text-forge.github.io/), powered by [Upptime](https://upptime.js.org/)."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://text-forge.github.io
    - title: Docs
      href: https://text-forge.github.io/docs
    - title: Online Marketplace
      href: https://text-forge.github.io/marketplace
